### ISSUE TITLE
cannot find attribute 'genome'

### ISSUE THREAD

**Issue by rckeerthivasan** [blajoie/hdf2tab#1]
I am trying to convert hdf5 file into tsv file. I am giving the basic command that is suggested in the usage but I am getting this error. Can you figure out why? I am trying to convert hdf5 files from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE77565

Traceback (most recent call last):
  File "scripts/hdf2tab.py", line 706, in <module>
    main()
  File "scripts/hdf2tab.py", line 95, in main
    genome=inhdf.attrs['genome'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
  File "/home/ken/miniconda2/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 58, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open (-------src-dir-------/h5py/h5a.c:2086)
KeyError: "Can't open attribute (Can't locate attribute: 'genome')"

**Comment by blajoie** [comment]
Hi - sorry about the delay (I have been traveling). I will look into this later today and push a fix if necessary.

**Comment by blajoie** [comment]
Hi,

The paper you linked looks to be from an different group, that may be using an entirely different HDF5 file structure to capture Hi-C matrices.  I doubt this tool will work as-is for the linked data.  I would suggest you contact the authors re. accessing the HDF5 data.

**Comment by wyt14** [comment]
I also meet this problem with hdf5 file from the ENCODE project.

python scripts/hdf2tab.py -i ENCFF912LCV.h5 -wm cis --chrs chr1
Traceback (most recent call last):
  File "/Share/home/yangxr/LabMem/ytwang/Program/hdf2tab-master/scripts/hdf2tab.py", line 706, in <module>
    main()
  File "/Share/home/yangxr/LabMem/ytwang/Program/hdf2tab-master/scripts/hdf2tab.py", line 95, in main
    genome=inhdf.attrs['genome'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "/Share/home/yangxr/anaconda2/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 58, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open (/tmp/pip-nCYoKW-build/h5py/h5a.c:2337)
KeyError: "Can't open attribute (Can't locate attribute: 'genome')"

**Comment by wyt14** [comment]
And the dataset is from your Lab

**Comment by blajoie** [comment]
Ah! Will take a look then.  Sounds like I simply need to make the genome
attreibute an optional field to support older versions of HiC-HDF5 files.

More soon

**Comment by blajoie** [comment]
Hi,

The script seems to work AOK for the ENCODE files.
e.g.
https://www.encodeproject.org/experiments/ENCSR079VIJ/

$python ~/git/hdf2tab/scripts/hdf2tab.py --input ENCFF298ZFN.h5 -v

hdf_blocksize 128
blocksize 128

building bin mask ...
        x bin_mask      6207
        y bin_mask      6207

writing tsv matrix
        6207x6207

Can you try again using the latest in git and the above file?
Perhaps you were using an older version?

**Comment by wyt14** [comment]
Thank you very much!
I have got the right results based on your guides.






On 8/8/2017 01:22，Bryan Lajoie<notifications@github.com> wrote：
Hi,

The script seems to work AOK for the ENCODE files.
e.g.
https://www.encodeproject.org/experiments/ENCSR079VIJ/

$python ~/git/hdf2tab/scripts/hdf2tab.py --input ENCFF298ZFN.h5 -v

hdf_blocksize 128
blocksize 128

building bin mask ...
x bin_mask 6207
y bin_mask 6207

writing tsv matrix
6207x6207

Can you try again using the latest in git and the above file?
Perhaps you were using an older version?

**Comment by wyt14** [comment]
Hi,
I am so sorry to disturb you. I have a question about the processed data in your Lab.
The following two files is about the nested-tads and tads regions.


ENCODE3-NCIH460-HindIII__hg19__genome__C-40000-iced.nested-tads.bed
ENCODE3-NCIH460-HindIII__hg19__genome__C-40000-iced.tads.bed


But, I find some regions in *.nested-tads.bed not be merged to the *.tads.bed, for example the marked by yellow label in the following figure.
So I want to know whether you filtered the the nested tads using some conditions and then merged to the tads file. If you did, which conditions you used.
Thank you very much!


And look forward to your reply!








--

Wang Yuting
School of Life Sciences
Tsinghua University
Beijing
P.R.China
